### ISSUE TITLE
python3 compatible?

### ISSUE THREAD

**Issue by lbazan** [dottedmag/archmage#10]
python3 compatible?

**Comment by tpokorra** [comment]
using 2to3, some things are solved automatically. See my patch here: https://src.fedoraproject.org/fork/tpokorra/rpms/archmage/blob/Python3Support/f/archmage-0.3.1-python3.patch

A bigger issue is the use of sgmllib, which is not part of Python3 anymore.
Should it be replaced with BeautifulSoup4? according to https://stackoverflow.com/questions/12167310/sgml-parser-for-python-3

**Comment by tpokorra** [comment]
a temporary workaround could be: `pip install sgmllib3k`

**Comment by tpokorra** [comment]
another issue is during runtime:

`archmage example.chm`

```
Traceback (most recent call last):
  File "/usr/bin/archmage", line 11, in <module>
    load_entry_point('archmage==0.3.1', 'console_scripts', 'archmage')()
  File "/usr/lib/python3.7/site-packages/archmod/cli.py", line 161, in main
    CHMFile(options.chmfile) or CHMDir(options.chmfile)
  File "/usr/lib/python3.7/site-packages/archmod/Cached.py", line 34, in __new__
    __instance = object.__new__(classtype, *args, **kwargs)
TypeError: object.__new__() takes exactly one argument (the type to instantiate)
```

see https://www.code-learner.com/how-to-use-python-__new__-method-example/

perhaps a solution in Cached.py:
```
    def __new__(classtype, *args, **kwargs):
        if not hasattr(classtype,'__instance'):
          __instance = super(Cached, classtype).__new__(classtype)
          __instance.cache = {}
        return __instance
```

**Comment by dottedmag** [comment]
Thank you, especially for `sgmllib3k` suggestion.

Working on Python 3 compatibility.

**Comment by dottedmag** [comment]
The version in `master` kind of works under Python 3.5+, however, I saw weird artefacts in the converted file. I'll look into it further to see if it is a regression.

Anyway, please try and see.

**Comment by dottedmag** [comment]
Done.
