### ISSUE TITLE
ValueError: signal only works in main thread 

### ISSUE THREAD

**Issue by bashu** [dottedmag/archmage#2]
I'm getting an a "ValueError: signal only works in main thread" in my error_log when attempting to view a .chm file with the archmage mod_python component in apache. FYI I am running 64-bit gentoo and the following versions of software:
apache-2.2.14
mod_python-3.3.1
beautifulsoup-3.0.7
chmlib-0.40
pychm-0.8.4
archmage-0.2.4

This FAQ seems to have information on the problem, but not being a programmer I'm not sure how to fix it:
http://twistedmatrix.com/trac/wiki/FrequentlyAskedQuestions#Igetexceptions.ValueError:signalonlyworksinmainthreadwhenItrytorunmyTwistedprogramWhatswrong

here is the complete output in error_log:
[Sun Jan 03 14:58:31 2010] [error] [client 127.0.0.1] mod_python (pid=2971, interpreter='localhost', phase='PythonHandler', handler='archmod.mod_chm'): Application error, referer: http://localhost/reference/gen/perl_programming.html
[Sun Jan 03 14:58:31 2010] [error] [client 127.0.0.1] ServerName: 'localhost', referer: http://localhost/reference/gen/perl_programming.html
[Sun Jan 03 14:58:31 2010] [error] [client 127.0.0.1] DocumentRoot: '/var/www/localhost/htdocs', referer: http://localhost/reference/gen/perl_programming.html
[Sun Jan 03 14:58:31 2010] [error] [client 127.0.0.1] URI: '/reference/pages/prog/perl/The_Perl_CD_Bookshelf_4.0_oreilly_2004.chm/', referer: http://localhost/reference/gen/perl_programming.html
[Sun Jan 03 14:58:31 2010] [error] [client 127.0.0.1] Location: None, referer: http://localhost/reference/gen/perl_programming.html
[Sun Jan 03 14:58:31 2010] [error] [client 127.0.0.1] Directory: None, referer: http://localhost/reference/gen/perl_programming.html
[Sun Jan 03 14:58:31 2010] [error] [client 127.0.0.1] Filename: '/nfs/media/reference/pages/prog/perl/The_Perl_CD_Bookshelf_4.0_oreilly_2004.chm', referer: http://localhost/reference/gen/perl_programming.html
[Sun Jan 03 14:58:31 2010] [error] [client 127.0.0.1] PathInfo: '/', referer: http://localhost/reference/gen/perl_programming.html
[Sun Jan 03 14:58:31 2010] [error] [client 127.0.0.1] Traceback (most recent call last):, referer: http://localhost/reference/gen/perl_programming.html
[Sun Jan 03 14:58:31 2010] [error] [client 127.0.0.1] File "/usr/lib64/python2.6/site-packages/mod_python/importer.py", line 1537, in HandlerDispatch\n default=default_handler, arg=req, silent=hlist.silent), referer: http://localhost/reference/gen/perl_programming.html
[Sun Jan 03 14:58:31 2010] [error] [client 127.0.0.1] File "/usr/lib64/python2.6/site-packages/mod_python/importer.py", line 1202, in _process_target\n module = import_module(module_name, path=path), referer: http://localhost/reference/gen/perl_programming.html
[Sun Jan 03 14:58:31 2010] [error] [client 127.0.0.1] File "/usr/lib64/python2.6/site-packages/mod_python/importer.py", line 304, in import_module\n return __import__(module_name, {}, {}, ['*']), referer: http://localhost/reference/gen/perl_programming.html
[Sun Jan 03 14:58:31 2010] [error] [client 127.0.0.1] File "/usr/lib64/python2.6/site-packages/archmod/mod_chm.py", line 5, in <module>\n from archmod.CHM import CHMFile, referer: http://localhost/reference/gen/perl_programming.html
[Sun Jan 03 14:58:31 2010] [error] [client 127.0.0.1] File "/usr/lib64/python2.6/site-packages/archmod/CHM.py", line 26, in <module>\n from archmod.chmtotext import chmtotext, referer: http://localhost/reference/gen/perl_programming.html
[Sun Jan 03 14:58:31 2010] [error] [client 127.0.0.1] File "/usr/lib64/python2.6/site-packages/archmod/chmtotext.py", line 11, in <module>\n signal.signal(signal.SIGPIPE, signal.SIG_DFL), referer: http://localhost/reference/gen/perl_programming.html
[Sun Jan 03 14:58:31 2010] [error] [client 127.0.0.1] ValueError: signal only works in main thread, referer: http://localhost/reference/gen/perl_programming.html

**Comment by dottedmag** [comment]
I'm inclined to add an option to `archmage -p` to serve a directory of .chm files and then document how to proxy requests from Apache and drop `mod_chm`.

What do you think?

**Comment by bashu** [comment]
agreed! do you have time for this one?

**Comment by dottedmag** [comment]
Yes. Will do.

**Comment by dottedmag** [comment]
The code is in, docs are not yet.

**Comment by dottedmag** [comment]
Looks like I don't have Apache anywhere handy to play with. Would you like to check out how to do proxying properly? From what I have read in the docs,  we need a `LocationMatch` for `*.chm/*` to be proxied. E.g. if CHMs from `/lala` are to be served, then `http://foobar.com/lala/barbar/foobar.chm/some/node` should be proxied  to `http://localhost:12345/barbar/foobar.chm/some/node`.

**Comment by bashu** [comment]
Yes, sure

**Comment by dottedmag** [comment]
Closed, the code is no longer in `master`.
