### ISSUE TITLE
Is it possible to convert Chinese chm to pdf?

### ISSUE THREAD

**Issue by ffffuturexu** [dottedmag/archmage#29]
Hi, thank you for this wonderful work. I triy to convert a chm file in Chinese to pdf. It works fine but the whole converted pdf is with unreadable characters. I think it might be the codec issue. So, I am wondering is it possible and how to accomplish Chinese chm conversion? Thank you in advance.

A Chinese chm file for test:
[chm in chinese.zip](https://github.com/dottedmag/archmage/files/8196439/chm.in.chinese.zip)

**Comment by dottedmag** [comment]
Looks OK for me after converting to a bunch of HTML files (running `archmage` without any further options).

<img width="844" alt="Screenshot 2022-03-07 at 23 26 40" src="https://user-images.githubusercontent.com/16120/157128515-f504c02b-fae4-4687-8f22-98746d147f29.png">

**Comment by ffffuturexu** [comment]
Thanks for the reply. I tried `archmage xxx.chm` and it did generate a folder with a bunch readable html files as you showed. However, I still would like to ask for any possible solutions for pdf conversion, because I have a big number of Chinese chm files, and I want to use your code to do batch processing. 

I may also have a try to dig into this after go through the whole work. So can I have some clues if I do this, like which functions should be looked at?
Thank you again.

**Comment by dottedmag** [comment]
Ah, PDF. It never worked well with non-Latin encodings, so I'd suggest to find another way to convert HTML to PDF.

**Comment by ffffuturexu** [comment]
Ah I see. Thank you for your tips again!
