### ISSUE TITLE
PHP help file in chm format (raise NameError) 

### ISSUE THREAD

**Issue by bashu** [dottedmag/archmage#3]
I have downloaded "Extended HTML Help" from http://www.php.net/download-docs.php
Then it wil be archmage started:
archmage -p 1111 /mnt/data/marek/Internet/help/php_ext/php_manual_en.chm

And after reload in http://localhost:1111/ there is following output:

localhost - - [26/Sep/2007 22:55:13] "GET / HTTP/1.1" 200 -
localhost - - [26/Sep/2007 22:55:14] "GET /arch_header.html HTTP/1.1" 200 -
localhost - - [26/Sep/2007 22:55:14] "GET /arch_frameset.html?page=_index.html HTTP/1.1" 200 -
localhost - - [26/Sep/2007 22:55:14] "GET /arch_contents.html HTTP/1.1" 200 -
localhost - - [26/Sep/2007 22:55:14] "GET /_index.html HTTP/1.1" 200 -
localhost - - [26/Sep/2007 22:55:14] "GET /arch_css.css HTTP/1.1" 200 -
localhost - - [26/Sep/2007 22:55:14] "GET /_script.js HTTP/1.1" 200 -
## localhost - - [26/Sep/2007 22:55:14] "GET /php_manual_prefs.js HTTP/1.1" 200 -

Exception happened during processing of request from ('127.0.0.1', 47811)
Traceback (most recent call last):
  File "SocketServer.py", line 222, in handle_request
    self.process_request(request, client_address)
  File "SocketServer.py", line 241, in process_request
    self.finish_request(request, client_address)
  File "SocketServer.py", line 254, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "SocketServer.py", line 521, in **init**
    self.handle()
  File "BaseHTTPServer.py", line 316, in handle
    self.handle_one_request()
  File "BaseHTTPServer.py", line 310, in handle_one_request
    method()
  File "/usr/lib/python2.4/site-packages/archmod/CHM.py", line 414, in do_GET
    self.wfile.write(self.server.CHM.get_entry_by_name(pagename))
  File "/usr/lib/python2.4/site-packages/archmod/CHM.py", line 89, in get_entry_by_name
    raise NameError, 'There is no %s' % name
## NameError: There is no /php_manual_prefs.js

localhost - - [26/Sep/2007 22:55:14] "GET /arch_css.css HTTP/1.1" 200 -
localhost - - [26/Sep/2007 22:55:17] "GET /icons/99.gif HTTP/1.1" 200 -
localhost - - [26/Sep/2007 22:55:17] "GET /icons/1.gif HTTP/1.1" 200 -
localhost - - [26/Sep/2007 22:55:17] "GET /icons/91.gif HTTP/1.1" 200 -
localhost - - [26/Sep/2007 22:55:17] "GET /icons/93.gif HTTP/1.1" 200 -
localhost - - [26/Sep/2007 22:55:17] "GET /icons/94.gif HTTP/1.1" 200 -

It looks  like HTML code is missing completely CSS formating. (php_manual_prefs.js exist and is working - tested in Windows in the same directory)

Should this be placed in a bug category?

**Comment by dottedmag** [comment]
I have tried it with current PHP documentation and it seems to work fine.
