### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SIGPIPE' on Windows

### ISSUE THREAD

**Issue by vhanla** [dottedmag/archmage#6]
Archmage installed but doesn't work well on Windows, here is the output after running it:
For instance `archmage -x afile.chm outputdir` and with other params too, it returns:

> Traceback (most recent call last):
>   File "C:\Python27\Scripts\archmage-script.py", line 11, in <module>
>     load_entry_point('archmage==0.3.1.post6.dev89962024', 'console_scripts', 'archmage')()
>   File "C:\Python27\lib\site-packages\pkg_resources__init__.py", line 565, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "C:\Python27\lib\site-packages\pkg_resources__init__.py", line 2589, in load_entry_point
>     return ep.load()
>   File "C:\Python27\lib\site-packages\pkg_resources__init__.py", line 2249, in load
>     return self.resolve()
>   File "C:\Python27\lib\site-packages\pkg_resources__init__.py", line 2255, in resolve
>     module = **import**(self.module_name, fromlist=['**name**'], level=0)
>   File "build\bdist.win32\egg\archmod\cli.py", line 63, in <module>
>   File "build\bdist.win32\egg\archmod\CHM.py", line 43, in <module>
>   File "build\bdist.win32\egg\archmod\chmtotext.py", line 27, in <module>
> AttributeError: 'module' object has no attribute 'SIGPIPE'

I built chmlib and pychm with this [batch file](https://gist.github.com/vhanla/f4ae372d47d4ece6b2214e07d2492139) and tested pychm with this [python script](http://stackoverflow.com/a/16193880/537347) which works, but Archmage doesn't.

**Comment by dottedmag** [comment]
Thanks, fixed in `master`.

Please let me know if there are other Windows issues, I don't have one handy to test.
