### ISSUE TITLE
DHTML menu and umlauts (again :)

### ISSUE THREAD

**Issue by de-ramon** [dottedmag/archmage#7]
Hi,
as user  Finkregh commented on 14 Apr 2015
"the DHTML menu in the left frame does not properly encode special characters (e.g. umlauts: EinfÃ¼hrung instead of Einführung)"

Example attached...
i_view32_deutsch.chm: IrfanView CHM-File German Language as i_view32_deutsch.zip

Generated file arch_contents.html showing Einfόhrung instead auf Einführung....
```
<html>
 <head>
  <title>i_view32_deutsch.chm</title>
  <LINK rel="Stylesheet" type="text/css" href="arch_css.css">
</head>

<body onload="setInterval('getLoc()', 500);">    
<script>
var lastDoc;
var contents = 
[
 ["Einfόhrung", "", "1", 
   ["Was ist IrfanView?", "hlp_irfanview.htm", "1"], 
   ["Installation", "hlp_installation.htm", "1"], 
   ["IrfanView deinstallieren", "hlp_uninstall.htm", "1"], 
   ["Hδufig gestellte Fragen (FAQs)", "hlp_frequently_asked.htm", "1"], 
   ["Unterstόtzte Formate", "hlp_supported_file.htm", "1"], 
   ["PlugIns", "hlp_plugins.htm", "1"], 
   ["IrfanView Shell Extension", "hlp_shellextension.htm", "1"], 
   ["Hotkeys/Tastenkombinationen", "hlp_hotkeys.htm", "1"], 
   ["Kommandozeilen-Optionen", "hlp_command_line.htm", "1"], 
   ["Symbolleiste", "hlp_toolbar.htm", "1"]], 
 ["Menό: Datei", "", "1", 
```
Inside HTML-Content the translation works fine: Menü is shown right...

Generated file hlp_open.htm

`<p>Klicken Sie auf das Datei-Men&uuml;, dann auf <span style="font-style: italic; font-weight: bold;">&Ouml;ffnen</span> (oder benutzen Sie das <span style="font-style: italic;">&Ouml;ffnen-</span>Werkzeug auf der <a href="hlp_toolbar.htm">Symbolleiste</a>). Ein <a href="javascript:hhpopuplink.textpopup(popid_1350385156,fontface,-1,-1,-1,-1)" class="popuplink">Dialog</a> erm&ouml;glicht Ihnen, eine Datei zum Gebrauch in <span class="f_Boldred">IrfanView</span> zu &ouml;ffnen.</p>
[i_view32_deutsch.zip](https://github.com/dottedmag/archmage/files/1097136/i_view32_deutsch.zip)

`

Could you have a look please?

Thanks,

ramon

**Comment by dottedmag** [comment]
Please try with current `master`: I have extracted `i_view_deutch.chm` and the encoding in the ToC is fine.
