### ISSUE TITLE
Broken encoding of Turkish characters in ToC

### ISSUE THREAD

**Issue by trappedinspacetime** [dottedmag/archmage#9]
I am on Ubuntu 16.04. I installed `archmage` package from default repository. I use archmage to serve a `chm` file which has non ASCII characters, some Turkish characters which are not ASCII such as `ı`  ,`ğ`, `ç`, `ö` etc. Non ASCII characters are replaced by strange letters such as `A%` in the titles of the linked pages. But the  Non ASCII characters  correctly rendered in the text in the pages. Is it related to python environment or does it stem from `html` rendering failure in Non ASCII characters, but the text in the pages are well.

**Comment by dottedmag** [comment]
Please send an example of a CHM file with this problem.

Encoding of topics' names is specified in the file, so this is either a broken CHM file or a broken encoding code.

**Comment by trappedinspacetime** [comment]
Thank you for responding.
I just tried it again with the file in this link [Osmanlıca-Türkçe chm file ](https://www.edebiyatogretmeni.org/dosya/download.php?file=8863a6fd8597e68cd0e01907aa2f7743)
Uppermost title looks like this:
 `OSMANLI TÃœRKÃ‡ESÄ° SÃ–ZLÃœÄÃœ (CHM).chm`
Most probably it's an issue originated from html encoding.

**Comment by dottedmag** [comment]
Thanks, will look into it.

**Comment by dottedmag** [comment]
```
		<param name="Name" value="S-Þ.htm">
		<param name="Local" value="S-&THORN;.htm">
```

This is a problem in the source CHM file. Please test under Windows to confirm if you can. I have checked that `iChm.app` behaves the same.
